-- MySQL Script generated by MySQL Workbench
-- Fri Mar 12 19:01:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_generation-game_online
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_generation-game_online
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_generation-game_online` DEFAULT CHARACTER SET utf8 ;
USE `db_generation-game_online` ;

-- -----------------------------------------------------
-- Table `db_generation-game_online`.`tb_classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_generation-game_online`.`tb_classes` (
  `id_classes` INT NOT NULL,
  `classe_classes` VARCHAR(45) NULL,
  `descrição_classes` VARCHAR(80) NULL,
  `poder_classe` VARCHAR(45) NULL,
  PRIMARY KEY (`id_classes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_generation-game_online`.`tb_personagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_generation-game_online`.`tb_personagens` (
  `id_personagens` INT NOT NULL,
  `nome_personagens` VARCHAR(50) NULL,
  `ataque_personagens` INT NULL,
  `defesa_personagens` INT NULL,
  `inteligencia_personagens` INT NULL,
  `tb_classes_id_classes` INT NOT NULL,
  PRIMARY KEY (`id_personagens`),
  INDEX `fk_tb_personagens_tb_classes_idx` (`tb_classes_id_classes` ASC) VISIBLE,
  CONSTRAINT `fk_tb_personagens_tb_classes`
    FOREIGN KEY (`tb_classes_id_classes`)
    REFERENCES `db_generation-game_online`.`tb_classes` (`id_classes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


insert into tb_classes (id_classes, classe_classes, descrição_classes, poder_classe) values 
#(1,'Guerreiro','especialisda em espadas','Corte de vento')
(2,'Assassino','Especialista em adagas','Rajadas de cortes'),
(3,'Arqueiro','Especialista em arcos','Chuva de flechas'),
(4,'Mago','Especialista em conjuração','Convocação das sombras'),
(5,'Curandeiro','Especialista em cura','Benção de Deus')
;

insert into tb_personagens (id_personagens, nome_personagens,ataque_personagens, defesa_personagens, inteligencia_personagens, tb_classes_id_classes ) values 
#(1, 'Maxixe', 300, 100, 5000,  4)
(2, 'Quiabo', 900, 150, 200,  2),
(3, 'Figado', 950, 200, 200,  3),
(4, 'Jilo', 150, 150, 900,  5),
(5, 'Açai', 300, 250, 900,  4),
(6, 'Moela', 300, 800, 200,  1),
(7, 'Lingua de Boi', 900, 150, 200,  2),
(8, 'Pé de Galinha', 300, 800, 200,  1);

insert into tb_personagens (id_personagens, nome_personagens,ataque_personagens, defesa_personagens, inteligencia_personagens, tb_classes_id_classes ) values 
(9, 'cascao', 300, 100, 5000,  4);


select * from tb_personagens;

select * from tb_personagens where ataque_personagens>300;

select * from tb_personagens where defesa_personagens between 100 and 200;

select * from tb_personagens where nome_personagens like "%c%";

select tb_personagens.nome_personagens, tb_classes.classe_classes
 from tb_personagens  
 inner join tb_classes 
 on  tb_personagens.tb_classes_id_classes = tb_classes.id_classes;


select tb_personagens.nome_personagens, tb_personagens.tb_classes_id_classes, tb_classes.classe_classes, tb_classes.id_classes 
from tb_personagens  inner join tb_classes
 on tb_personagens.tb_classes_id_classes = tb_classes.id_classes
where tb_personagens.tb_classes_id_classes = 4;
